# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qs', '0006_auto_20170819_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
