# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qs', '0008_auto_20170822_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='voters',
        ),
        migrations.RemoveField(
            model_name='question',
            name='voters',
        ),
    ]
