---QUESTIONS---
INSERT INTO public.qs_question (id, title, content, created, author_id, votes, slug) VALUES (17, 'Understand fast prime numbers generator', 'Can someone please describe how this code works?', '2017-08-18 11:46:08.282000', 1, 0, 'understand-fast-prime-numbers-generator');
INSERT INTO public.qs_question (id, title, content, created, author_id, votes, slug) VALUES (5, 'How can i return stdout to value on python?', 'I made some script. I want return stdout to value on python.
But my script not work.', '2017-08-18 11:32:25.648000', 1, 0, 'how-can-i-return-stdout-to-value-on-python');
INSERT INTO public.qs_question (id, title, content, created, author_id, votes, slug) VALUES (6, 'How to IMPLEMENT A SIMPLE PYTHON DECORATOR Program?', 'Please help to learn how to Implement a Python decorator that should take whatever the decorated function returns, and writes it to a file in a new line.', '2017-08-18 11:33:13.307000', 1, 0, 'how-to-implement-a-simple-python-decorator-program');
INSERT INTO public.qs_question (id, title, content, created, author_id, votes, slug) VALUES (7, 'TensorFlow?', 'The array is [1.5, 2.3, 4.7, 2.9] and its mean is 2.85.
I want get the array is [4.7, 2.9] and calculate its mean.
How can I do that with TensorFlow?', '2017-08-18 11:34:54.032000', 1, 0, 'tensorflow');
INSERT INTO public.qs_question (id, title, content, created, author_id, votes, slug) VALUES (8, 'Running python code on a web-page', 'At the moment I have a chat bot written in python on my laptop. I need to launch it on a web page so it can be accessed from the internet. What do I need to set up to make it happen?', '2017-08-18 11:35:59.223000', 1, 0, 'running-python-code-on-a-web-page');
INSERT INTO public.qs_question (id, title, content, created, author_id, votes, slug) VALUES (9, 'Django get model by querystring', 'I want the user to be able to pass a querystring in url like https://example.com/models?id=232. But the query string is optional. so https://example/models should work too.', '2017-08-18 11:36:32.767000', 1, 0, 'django-get-model-by-querystring');
INSERT INTO public.qs_question (id, title, content, created, author_id, votes, slug) VALUES (10, 'SWIG2 with NUMPY', 'I am trying to build a SWIG2.0 interface for my C++ class. Only requirement is that I need to be able to pass a numpy array from python into the C++ class.', '2017-08-18 11:37:18.398000', 1, 0, 'swig2-with-numpy');
INSERT INTO public.qs_question (id, title, content, created, author_id, votes, slug) VALUES (11, 'Call definite folder name and value in dictionary in Python', 'I want to write function that will copy structure and content of one root folder to another one (that already contains most of files in the initial folder and function must compare files and directories and copy if it is not exists in destination folder). Name of folders are the dict.values().', '2017-08-18 11:41:28.407000', 1, 0, 'call-definite-folder-name-and-value-in-dictionary-in-python');
INSERT INTO public.qs_question (id, title, content, created, author_id, votes, slug) VALUES (12, 'ValueError: invalid literal for float(): “320” for a normal string', 'I just encountered a very strange problem: I try to turn a string to float and then back to str.', '2017-08-18 11:41:56.652000', 1, 0, 'valueerror-invalid-literal-for-float-320-for-a-normal-string');
INSERT INTO public.qs_question (id, title, content, created, author_id, votes, slug) VALUES (13, 'Importing Bootstrap SCSS into a Django project', 'Do I assume correctly, that in my custom SCSS, I can not access the variables of Bootstrap (because it''s a compiled CSS, not an SCSS)? I tried to change $spacer: 1rem !default; and it didn''t work.', '2017-08-18 11:42:22.360000', 1, 0, 'importing-bootstrap-scss-into-a-django-project');
INSERT INTO public.qs_question (id, title, content, created, author_id, votes, slug) VALUES (14, 'Best practice for tests that run on multiple input files in Python', 'Most test frameworks assume that "1 test = 1 Python method/function", and consider a test as passed when the function executes without raising assertions.', '2017-08-18 11:42:51.159000', 1, 0, 'best-practice-for-tests-that-run-on-multiple-input-files-in-python');
INSERT INTO public.qs_question (id, title, content, created, author_id, votes, slug) VALUES (16, 'What curve_fit to use in scipy for this dataset?', 'I am trying to fit a curve to a set of data points.', '2017-08-18 11:45:49.185000', 1, 0, 'what-curve_fit-to-use-in-scipy-for-this-dataset');
INSERT INTO public.qs_question (id, title, content, created, author_id, votes, slug) VALUES (18, 'Pandas how to use pd.cut()', 'I am surprised that 0 is not in (0, 30], what should I do to categorize 0 as (0, 30]?', '2017-08-18 11:46:27.247000', 1, 0, 'pandas-how-to-use-pdcut');
INSERT INTO public.qs_question (id, title, content, created, author_id, votes, slug) VALUES (19, 'Django admin page adding save as pdf button', 'In the below code I have added a save as pdf button in admin page by customizing it.While I''m clicking the save as pdf button it should display the details of the current page in pdf format.I couldn''t able to retrieve the separate data of the current page to display it in the pdf form(my_template.html).How to do it? Thanks in advance.', '2017-08-18 11:46:45.683000', 1, 0, 'django-admin-page-adding-save-as-pdf-button');
INSERT INTO public.qs_question (id, title, content, created, author_id, votes, slug) VALUES (20, 'How to stop QuickBooks Online API oAuth 2 issue with client_id parameter?', 'Which I have successfully done using requests-oauthlib and correctly get the response from the QBO API with the code (to exchange for token), the realmid (the actual QBO company file) and the state.', '2017-08-18 11:47:03.638000', 1, 0, 'how-to-stop-quickbooks-online-api-oauth-2-issue-with-client_id-parameter');
INSERT INTO public.qs_question (id, title, content, created, author_id, votes, slug) VALUES (21, 'How to add additional sum column to the DataFrame based on specific column groups?', 'What I want is first groupby col1 and then sum col2 columns of the groups, finally add the sum to the DataFrame and get.', '2017-08-18 11:47:22.304000', 1, 0, 'how-to-add-additional-sum-column-to-the-dataframe-based-on-specific-column-groups');
INSERT INTO public.qs_question (id, title, content, created, author_id, votes, slug) VALUES (22, 'hat does this tornado error message mean?', 'I get this error, no idea why, since nothing in the stacktrace is my code and every error is tornado code.', '2017-08-18 11:47:50.808000', 1, 0, 'hat-does-this-tornado-error-message-mean');
INSERT INTO public.qs_question (id, title, content, created, author_id, votes, slug) VALUES (23, 'Run python script from python GUI(Pyjamas)', 'I need run a python program from a Python GUI(Pyjamas).When ever I press a button a python program on a specific path should run. any help on this???', '2017-08-18 11:48:08.352000', 1, 0, 'run-python-script-from-python-guipyjamas');
INSERT INTO public.qs_question (id, title, content, created, author_id, votes, slug) VALUES (24, 'Can not import patterns in django 1.11.4', 'My project urls.py is as follows:
from django.conf.urls import include, url
from django.contrib import admin
admin.autodiscover()
urlpadrtterns = [
url(r''^admin/'', include(admin.site.urls)),
url(r''^myapp/'', include(''myapp.urls'')),
]', '2017-08-18 11:49:07.239000', 1, 0, 'can-not-import-patterns-in-django-1114');
INSERT INTO public.qs_question (id, title, content, created, author_id, votes, slug) VALUES (25, 'Caching in Azure Functions using python', 'I am using Azure Queue as a trigger in my azure function.
My azure function connects to mongoDB fetch some collections.
Some of this collection can vary from 100 Documents to 1 Million Documents. Some collections are common for all the queue jobs.
So I need to cache those common collections. I don''t want to use any external caching services(Azure Redis Server etc).
Is there a way to use File Caching(or any other kind of caching)?
I am using Python 3.5.2.', '2017-08-18 11:49:34.282000', 1, 0, 'caching-in-azure-functions-using-python');
INSERT INTO public.qs_question (id, title, content, created, author_id, votes, slug) VALUES (26, 'Using a metaclass to substitute a class definition?', 'Python 3.6
I''m trying to modify the behavior of a third party library.
I don''t want to directly change the source code.', '2017-08-18 11:50:08.230000', 1, 0, 'using-a-metaclass-to-substitute-a-class-definition');
INSERT INTO public.qs_question (id, title, content, created, author_id, votes, slug) VALUES (27, 'scrapyd-client command not found', 'down vote
favorite
I''d just installed the scrapyd-client(1.1.0) in a virtualenv, and run command ''scrapyd-deploy'' successfully, but when I run ''scrapyd-client'', the terminal said: command not found: scrapyd-client.
According to the readme file(https://github.com/scrapy/scrapyd-client), there should be a ''scrapyd-client'' command.
I had checked the path ''/lib/python2.7/site-packages/scrapyd-client'', only ''scrapyd-deploy'' in the folder.
Is the command ''scrapyd-client'' being removed for now?', '2017-08-18 11:50:25.823000', 1, 0, 'scrapyd-client-command-not-found');
---
